name: Playwright Tests
on:

  pull_request:
    branches: [master]
  
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze result
        uses: ./.github/action-github
      
  close_PR:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: test
    if: ${{ always() && !contains(needs.*.result, 'success') && (contains(needs.*.result, 'failure')) }}
    steps: 
    - uses: actions/checkout@v3
    - name: Close PR
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr close "$PR_URL"
      
  merge_PR:
    permissions: write-all
    name: merge_PR
    environment: dev
    runs-on: ubuntu-latest
    needs: test
    if: ${{ contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    steps:
      - uses: actions/checkout@v3
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
         PR_URL: ${{ github.event.pull_request.html_url }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
