name: Playwright Tests
on:
  push:
    branches: AJulianah-patch1
  
jobs:
  test:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze result
        uses: ./.github/action-github
        id: FAILED
      - name: Calculator
        run: exprR ${{ steps.FAILED.outputs.FAILED }}+10.231 | bc
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: master
